name: dumi - deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build & deploy
        env:
          BUILD_ID: ${{ github.sha }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: |
          yarn install
          yarn bootstrap
          yarn build
          yarn doc:build
          now --token=$ZEIT_TOKEN --prod --force --scope umijs
